package org.pixode.dynadoc.tidb

// Sorts the keys by their UTF-8 encoding, without ignoring trailing spaces
private const val KEY_COLLATION = "utf8mb4_0900_bin"
// The user variables holding the parameter and the result of the update script
private const val OPERATIONS = "@dynadoc_operations"
private const val CONFLICT = "@dynadoc_conflict"
// Reads each row using its primary key, rather than reading the whole table
private const val ROW_LOOKUP = "/*+ INL_JOIN(t) */"

const val MAX_KEY_LENGTH = 255
// The number of indexes generated to read the parameter of the update script
const val MAX_UPDATE_SIZE = 10000

class TiDbTable(table: String) {
    val tableName: String = table.split('.').joinToString(".", transform = ::quoteIdentifier)

    private val rowFilter: String =
        "t.$PARTITION_HASH = CRC32(o.$PARTITION_KEY) AND t.$PARTITION_KEY = o.$PARTITION_KEY " +
            "AND t.$LOCAL_KEY = o.$LOCAL_KEY"

    // The rows described by the parameter of the update script, which is parsed once per statement. Their indexes are
    // generated by combining digits, as recursive queries are slow.
    private val operations: String =
        """
        WITH digits AS (
            ${(0..9).joinToString(" UNION ALL ") { digit -> "SELECT $digit AS d" }}
        ), numbers AS (
            SELECT d0.d + 10 * d1.d + 100 * d2.d + 1000 * d3.d AS i FROM digits d0, digits d1, digits d2, digits d3
        ), parameter AS (
            SELECT CAST($OPERATIONS AS JSON) AS elements
        ), elements AS (
            SELECT i, JSON_EXTRACT(elements, CONCAT('$[', i, ']')) AS element
            FROM parameter JOIN numbers ON i < JSON_LENGTH(elements)
        ), operations AS (
            SELECT
                i,
                JSON_UNQUOTE(JSON_EXTRACT(element, '$.$PARTITION_KEY')) COLLATE $KEY_COLLATION AS $PARTITION_KEY,
                JSON_UNQUOTE(JSON_EXTRACT(element, '$.$LOCAL_KEY')) COLLATE $KEY_COLLATION AS $LOCAL_KEY,
                CAST(JSON_EXTRACT(element, '$.$VERSION') AS SIGNED) AS $VERSION,
                IF(
                    JSON_TYPE(JSON_EXTRACT(element, '$.$BODY')) = 'NULL', NULL, JSON_EXTRACT(element, '$.$BODY')
                ) AS $BODY,
                JSON_UNQUOTE(JSON_EXTRACT(element, '$.$CHECK')) = 'true' AS is_check
            FROM elements
        )
        """.trimIndent()

    /**
     * Creates the table, clustered by hash of the partition key, then partition key, then local key, so that the
     * partitions are spread evenly across the regions, and the documents of a partition are stored together and
     * sorted by local key.
     */
    fun createTableSql(): String {
        return """
            CREATE TABLE IF NOT EXISTS $tableName (
                $PARTITION_HASH BIGINT NOT NULL,
                $PARTITION_KEY VARCHAR($MAX_KEY_LENGTH) CHARACTER SET utf8mb4 COLLATE $KEY_COLLATION NOT NULL,
                $LOCAL_KEY VARCHAR($MAX_KEY_LENGTH) CHARACTER SET utf8mb4 COLLATE $KEY_COLLATION NOT NULL,
                $VERSION BIGINT NOT NULL,
                $BODY JSON,
                PRIMARY KEY ($PARTITION_HASH, $PARTITION_KEY, $LOCAL_KEY) CLUSTERED
            )
            """.trimIndent()
    }

    /**
     * Returns the script updating the documents described by its parameter (see [RowMapper.fromDocuments]). TiDB
     * doesn't support stored procedures, so the statements of the script are sent together, in a single request.
     *
     * The last statement of the script returns null when the documents have been updated. When a document doesn't
     * have the expected version, none of the documents is updated, and the index of that document is returned. The
     * script fails without committing its transaction, which must then be rolled back, when a document is locked or
     * created by another transaction.
     */
    fun updateScript(): String {
        val statements: List<String> = listOf(
            "SET $OPERATIONS = ?",
            // The versions are checked after the rows have been locked, so they must be read as they are then
            "SET TRANSACTION ISOLATION LEVEL READ COMMITTED",
            "BEGIN PESSIMISTIC",
            // Lock the documents without waiting, so that a concurrent write to them causes a conflict
            """
            $operations
            SELECT $ROW_LOOKUP t.$VERSION FROM $tableName t JOIN operations o ON $rowFilter FOR UPDATE NOWAIT
            """.trimIndent(),
            """
            SET $CONFLICT = (
                $operations
                SELECT $ROW_LOOKUP MIN(o.i) FROM operations o LEFT JOIN $tableName t ON $rowFilter
                WHERE COALESCE(t.$VERSION, 0) <> o.$VERSION
            )
            """.trimIndent(),
            // Fails if a document has been created by a concurrent transaction
            """
            INSERT INTO $tableName ($PARTITION_HASH, $PARTITION_KEY, $LOCAL_KEY, $VERSION, $BODY)
            $operations
            SELECT CRC32(o.$PARTITION_KEY), o.$PARTITION_KEY, o.$LOCAL_KEY, 1, o.$BODY FROM operations o
            WHERE o.$VERSION = 0 AND $CONFLICT IS NULL
            """.trimIndent(),
            // A checked document that doesn't exist is inserted then deleted, so that a concurrent insert of the same
            // document causes a conflict
            """
            $operations
            DELETE $ROW_LOOKUP t FROM $tableName t JOIN operations o ON $rowFilter
            WHERE o.is_check AND o.$VERSION = 0 AND $CONFLICT IS NULL
            """.trimIndent(),
            """
            $operations
            UPDATE $ROW_LOOKUP $tableName t JOIN operations o ON $rowFilter
            SET t.$VERSION = o.$VERSION + 1, t.$BODY = o.$BODY
            WHERE NOT o.is_check AND o.$VERSION > 0 AND $CONFLICT IS NULL
            """.trimIndent(),
            "COMMIT",
            "SET $OPERATIONS = NULL",
            "SELECT CAST($CONFLICT AS SIGNED)",
        )

        return statements.joinToString(";\n")
    }

    private fun quoteIdentifier(identifier: String): String = "`${identifier.replace("`", "``")}`"
}
